---
- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
    
- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      # it is usually recommended to specify which version you want to install
      - kubelet=1.23.6-00
      - kubeadm=1.23.6-00
      - kubectl=1.23.6-00
      
- name: hold kubernetes binary versions (prevent from being updated)
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
        
# this has to do with nodes having different internal/external/mgmt IPs
# {{ node_ip }} comes from vagrant, which I'm not using yet
#  - name: Configure node ip - 
#    lineinfile:
#      path: /etc/default/kubelet
#      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    
- name: add ubuntu user to docker
  user:
    name: ubuntu
    group: docker

- name: reboot to apply swap disable
  reboot:
    reboot_timeout: 180 #allow 